FROM node:16-alpine
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
RUN chown -R node:node /app/node_modules
CMD ["npm", "run", "start"]
