FROM node:14.14.0-alpine
WORKDIR '/app'
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
COPY ./package.json ./
RUN npm install
COPY . .
RUN chown -R node:node /app/node_modules
CMD ["npm", "run", "dev"]
